import { getBaseTemplateName } from './utils.js';

export function toJson(siteData) {
  return JSON.stringify(siteData, null, 2);
}

export function toMarkdown(siteData) {
  const { web, lists, warnings } = siteData;
  const lines = [
    '# SharePoint Dev Lens Report',
    '',
    `**Site:** ${web.Url}`,
    `**Title:** ${web.Title}`,
    `**Generated:** ${new Date(siteData.fetchedAt).toLocaleString()}`,
    `**Web ID:** \`${web.Id}\``,
    `**Template:** ${web.WebTemplate}#${web.Configuration}`,
    `**Language (LCID):** ${web.Language}`,
    '',
    '## Lists & Libraries',
    '',
    '| Title | GUID | Template | Items | Versioning | Unique Perms |',
    '|-------|------|----------|-------|------------|--------------|',
  ];

  for (const l of lists) {
    lines.push(
      `| ${l.Title} | \`${l.Id}\` | ${getBaseTemplateName(l.BaseTemplate)}` +
      ` | ${l.ItemCount.toLocaleString()} | ${l.EnableVersioning ? '✓' : '✗'}` +
      ` | ${l.HasUniqueRoleAssignments ? '⚠' : '–'} |`
    );
  }

  if (warnings.length) {
    lines.push('', '## Governance Warnings', '');
    for (const w of warnings) {
      const icon = w.severity === 'error' ? '🔴' : w.severity === 'warning' ? '🟡' : '🔵';
      lines.push(`${icon} **[${w.category}] ${w.title}**`);
      lines.push(`   ${w.description}`, '');
    }
  }

  lines.push('---', '*Generated by SharePoint Dev Lens*');
  return lines.join('\n');
}

export function toCsv(siteData) {
  const rows = [
    ['Title','GUID','Template','Items','Hidden','Versioning','ContentApproval','UniquePerms'].join(','),
  ];
  for (const l of siteData.lists) {
    rows.push([
      `"${l.Title.replace(/"/g, '""')}"`,
      l.Id,
      getBaseTemplateName(l.BaseTemplate),
      l.ItemCount,
      l.Hidden,
      l.EnableVersioning,
      l.EnableModeration,
      l.HasUniqueRoleAssignments,
    ].join(','));
  }
  return rows.join('\n');
}

export function download(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
